#include "shader_effect.h"
#include <d2d1effectauthor.h>
#include <atomic>
#include <cmath>
#include <cstring>
#include <new>
#include "lumen_shader_ps.h"   // generated by fxc at build time (g_lumen_shader_ps)
#include "lumen/win_undef.h"

namespace lumen {
namespace {

// {6C1F0F3B-5B8E-4C3F-9A51-2B7E4D0C9A11}
constexpr CLSID kShaderEffectClsid{0x6c1f0f3b, 0x5b8e, 0x4c3f, {0x9a, 0x51, 0x2b, 0x7e, 0x4d, 0x0c, 0x9a, 0x11}};
// {0E6B4C77-2D1A-4F7B-8C3E-6A5D9F1B2E44}
constexpr GUID kShaderGuid{0x0e6b4c77, 0x2d1a, 0x4f7b, {0x8c, 0x3e, 0x6a, 0x5d, 0x9f, 0x1b, 0x2e, 0x44}};

constexpr wchar_t kEffectXml[] =
    L"<?xml version='1.0'?>"
    L"<Effect>"
    L"<Property name='DisplayName' type='string' value='LUMEN Shader'/>"
    L"<Property name='Author' type='string' value='LUMEN'/>"
    L"<Property name='Category' type='string' value='Source'/>"
    L"<Property name='Description' type='string' value='Procedural monochrome light'/>"
    L"<Inputs/>"
    L"<Property name='Constants' type='blob'>"
    L"<Property name='DisplayName' type='string' value='Constants'/>"
    L"</Property>"
    L"</Effect>";

class ShaderEffectImpl final : public ID2D1EffectImpl, public ID2D1DrawTransform {
public:
    static HRESULT CALLBACK Create(IUnknown** out) {
        if (!out) return E_POINTER;
        auto* impl = new (std::nothrow) ShaderEffectImpl();
        *out = impl ? static_cast<ID2D1EffectImpl*>(impl) : nullptr;
        return impl ? S_OK : E_OUTOFMEMORY;
    }

    static HRESULT CALLBACK SetConstantsBinding(IUnknown* effect, const BYTE* data, UINT32 size) {
        return FromUnknown(effect)->SetConstants(data, size);
    }
    static HRESULT CALLBACK GetConstantsBinding(const IUnknown* effect, BYTE* data, UINT32 size,
                                                UINT32* actual) {
        return FromUnknown(const_cast<IUnknown*>(effect))->GetConstants(data, size, actual);
    }

    // IUnknown
    IFACEMETHODIMP QueryInterface(REFIID riid, void** out) override {
        if (!out) return E_POINTER;
        if (riid == __uuidof(ID2D1EffectImpl) || riid == __uuidof(IUnknown)) {
            *out = static_cast<ID2D1EffectImpl*>(this);
        } else if (riid == __uuidof(ID2D1DrawTransform) || riid == __uuidof(ID2D1Transform) ||
                   riid == __uuidof(ID2D1TransformNode)) {
            *out = static_cast<ID2D1DrawTransform*>(this);
        } else {
            *out = nullptr;
            return E_NOINTERFACE;
        }
        AddRef();
        return S_OK;
    }
    IFACEMETHODIMP_(ULONG) AddRef() override { return ++refs_; }
    IFACEMETHODIMP_(ULONG) Release() override {
        const ULONG left = --refs_;
        if (left == 0) delete this;
        return left;
    }

    // ID2D1EffectImpl
    IFACEMETHODIMP Initialize(ID2D1EffectContext* context, ID2D1TransformGraph* graph) override {
        if (!context || !graph) return E_INVALIDARG;
        HRESULT hr = context->LoadPixelShader(kShaderGuid, g_lumen_shader_ps,
                                              static_cast<UINT32>(sizeof(g_lumen_shader_ps)));
        if (FAILED(hr)) return hr;
        return graph->SetSingleTransformNode(static_cast<ID2D1DrawTransform*>(this));
    }
    IFACEMETHODIMP PrepareForRender(D2D1_CHANGE_TYPE) override {
        if (!draw_info_) return E_FAIL;
        return draw_info_->SetPixelShaderConstantBuffer(reinterpret_cast<const BYTE*>(&constants_),
                                                        static_cast<UINT32>(sizeof(constants_)));
    }
    IFACEMETHODIMP SetGraph(ID2D1TransformGraph*) override { return E_NOTIMPL; }

    // ID2D1DrawTransform
    IFACEMETHODIMP SetDrawInfo(ID2D1DrawInfo* info) override {
        if (!info) return E_INVALIDARG;
        if (draw_info_) draw_info_->Release();
        draw_info_ = info;
        draw_info_->AddRef();
        return draw_info_->SetPixelShader(kShaderGuid);
    }

    // ID2D1Transform -- a generator: no inputs, output is exactly size[] pixels.
    IFACEMETHODIMP MapOutputRectToInputRects(const D2D1_RECT_L*, D2D1_RECT_L*,
                                             UINT32 count) const override {
        return count == 0 ? S_OK : E_INVALIDARG;
    }
    IFACEMETHODIMP MapInputRectsToOutputRect(const D2D1_RECT_L*, const D2D1_RECT_L*, UINT32 count,
                                             D2D1_RECT_L* output,
                                             D2D1_RECT_L* opaque) override {
        if (count != 0 || !output || !opaque) return E_INVALIDARG;
        *output = OutputRect();
        *opaque = D2D1_RECT_L{0, 0, 0, 0};
        return S_OK;
    }
    IFACEMETHODIMP MapInvalidRect(UINT32, D2D1_RECT_L, D2D1_RECT_L* invalid) const override {
        if (!invalid) return E_INVALIDARG;
        *invalid = OutputRect();
        return S_OK;
    }

    // ID2D1TransformNode
    IFACEMETHODIMP_(UINT32) GetInputCount() const override { return 0; }

private:
    ShaderEffectImpl() = default;
    ~ShaderEffectImpl() {
        if (draw_info_) draw_info_->Release();
    }

    static ShaderEffectImpl* FromUnknown(IUnknown* unknown) {
        // Create hands D2D the ID2D1EffectImpl sub-object; bindings receive that pointer back.
        return static_cast<ShaderEffectImpl*>(reinterpret_cast<ID2D1EffectImpl*>(unknown));
    }

    D2D1_RECT_L OutputRect() const {
        const LONG w = static_cast<LONG>(std::ceil(constants_.size[0] > 0.0f ? constants_.size[0] : 0.0f));
        const LONG h = static_cast<LONG>(std::ceil(constants_.size[1] > 0.0f ? constants_.size[1] : 0.0f));
        return D2D1_RECT_L{0, 0, w, h};
    }

    HRESULT SetConstants(const BYTE* data, UINT32 size) {
        if (!data || size != sizeof(constants_)) return E_INVALIDARG;
        std::memcpy(&constants_, data, sizeof(constants_));
        return S_OK;
    }
    HRESULT GetConstants(BYTE* data, UINT32 size, UINT32* actual) const {
        if (actual) *actual = static_cast<UINT32>(sizeof(constants_));
        if (!data) return S_OK;
        if (size < sizeof(constants_)) return E_NOT_SUFFICIENT_BUFFER;
        std::memcpy(data, &constants_, sizeof(constants_));
        return S_OK;
    }

    std::atomic<ULONG> refs_{1};
    ID2D1DrawInfo* draw_info_ = nullptr;
    ShaderConstants constants_{};
};

bool RegisterShaderEffect(ID2D1DeviceContext* dc) {
    ID2D1Factory* factory = nullptr;
    dc->GetFactory(&factory);
    if (!factory) return false;
    ID2D1Factory1* factory1 = nullptr;
    const HRESULT qi = factory->QueryInterface(__uuidof(ID2D1Factory1),
                                               reinterpret_cast<void**>(&factory1));
    factory->Release();
    if (FAILED(qi) || !factory1) return false;
    const D2D1_PROPERTY_BINDING bindings[] = {
        {L"Constants", &ShaderEffectImpl::SetConstantsBinding, &ShaderEffectImpl::GetConstantsBinding},
    };
    const HRESULT hr = factory1->RegisterEffectFromString(kShaderEffectClsid, kEffectXml, bindings,
                                                          1, &ShaderEffectImpl::Create);
    factory1->Release();
    return SUCCEEDED(hr);
}

} // namespace

ID2D1Effect* CreateShaderEffect(ID2D1DeviceContext* dc) {
    if (!dc) return nullptr;
    ID2D1Effect* effect = nullptr;
    // Registration is per factory; try the fast path first, register once on miss.
    if (FAILED(dc->CreateEffect(kShaderEffectClsid, &effect)) || !effect) {
        effect = nullptr;
        if (!RegisterShaderEffect(dc)) return nullptr;
        if (FAILED(dc->CreateEffect(kShaderEffectClsid, &effect)) || !effect) return nullptr;
    }
    return effect;
}

bool SetShaderConstants(ID2D1Effect* effect, const ShaderConstants& constants) {
    if (!effect) return false;
    return SUCCEEDED(effect->SetValue(0, D2D1_PROPERTY_TYPE_BLOB,
                                      reinterpret_cast<const BYTE*>(&constants),
                                      static_cast<UINT32>(sizeof(constants))));
}

} // namespace lumen
